### ISSUE TITLE
initial first setup

### ISSUE THREAD

**Issue by mattyhansen** [mattyhansen/symfony5-rest-api#1]
### Tasks

- [x] `composer create-project symfony/skeleton symfony5-rest-api`
- [x] `composer require symfony/serializer-pack` (required for rest-bundle)
- [x] `composer require friendsofsymfony/rest-bundle`
